### ISSUE TITLE
check and fix e-mail forms

### ISSUE THREAD

**Issue by adamsteer** [foss4g-oceania/foss4g-sotm-oceania-2020#10]
Ensure that wherever an option exists to sign up for communications, OR submit feedback, that the form points at appropriate e-mail addresses

**Comment by jonah-sullivan** [comment]
fixed it #18

**Comment by EdwinLiavaa** [comment]
Should this be closed now?

**Comment by jonah-sullivan** [comment]
I think @adamsteer will make a pull request, so keep it open for now.

**Comment by EdwinLiavaa** [comment]
Very well noted...cheers!

**Comment by jonah-sullivan** [comment]
The mailchimp signup form has had information about contact details usage added to it.

Recommend close this issue.

**Comment by EdwinLiavaa** [comment]
Looks good

**Comment by EdwinLiavaa** [comment]
agree
