### ISSUE TITLE
Remove "Free of Charge" and "No Registration"

### ISSUE THREAD

**Issue by jonah-sullivan** [foss4g-oceania/foss4g-sotm-oceania-2020#21]
I'm having trouble finding the part of the website to edit.

Please remove the text because hub managers might charge (for venue/catering) and registration will be required to attend a hub.

![image](https://user-images.githubusercontent.com/11877822/90998215-ec7c9000-e606-11ea-9bad-7bef33cff157.png)

**Comment by EdwinLiavaa** [comment]
Done!
