### ISSUE TITLE
Footer links still contain info from SotM

### ISSUE THREAD

**Issue by johnwbryant** [foss4g-oceania/foss4g-sotm-oceania-2020#22]
The content at https://2020.foss4g-oceania.org/cfp/ and https://2020.foss4g-oceania.org/cfp/academic/, linked from the footer, contains a bunch of info from the State of the Map conference.

Can we remove this content?

**Comment by EdwinLiavaa** [comment]
Done, since there are no existing calls for abstracts, I've put it to be announced.
