### ISSUE TITLE
Update Map Pins

### ISSUE THREAD

**Issue by jonah-sullivan** [foss4g-oceania/foss4g-sotm-oceania-2020#23]
@FidelChe , Please update the map pins with these values:

Apia, Samoa | -13.833; -171.750
Auckland, New Zealand | -36.84056; 174.74000
Cairns, Australia | -16.93028; 145.77028
Canberra, Australia | -35.29306; 149.12694
Christchurch, New Zealand | -43.53000; 172.62028
Hobart, Australia | -42.88056; 147.32500
Melbourne, Australia | -37.81361; 144.96306
Perth, Australia | -31.95222; 115.85889
Rarotonga, Cook Islands | -21.233; -159.783
Suva, Fiji | -18.1416; 178.4419

There will be a future requirement to make a page for each hub and link these pins to their page.

**Comment by EdwinLiavaa** [comment]
Have some issue with adding more map objects "pins" to the map canvas. The map just don't load. Investigating why and see how to fix.

**Comment by jonah-sullivan** [comment]
Yeah, I found the page with the pins, and I thought about editing it, but I
figured I should leave it to the experts.

Thanks for getting onto it.

**Comment by EdwinLiavaa** [comment]
It was human error, i duplicated Perth Hub :)..It's done now

**Comment by jonah-sullivan** [comment]
Congratulations. It totally works, and you made the logo much better.

Great work!

**Comment by EdwinLiavaa** [comment]
Thanks n most welcome...cheers

**Comment by jonah-sullivan** [comment]
Looks Good
