### ISSUE TITLE
Map Pins and Logos

### ISSUE THREAD

**Issue by jonah-sullivan** [foss4g-oceania/foss4g-sotm-oceania-2020#27]
The map pins look good and sleek, but unfortunately the parent organisation requires FOSS4G conferences use the ["FOSS4G Ribbon".](https://wiki.osgeo.org/wiki/FOSS4G_Handbook#Logo)

I prefer the way that the pins and logo look now, but we're gonna have to change it.

**Comment by EdwinLiavaa** [comment]
All good, will change it back to the original Sotm logo?

**Comment by jonah-sullivan** [comment]
Yeah, I think so.

Actually, the regional conferences have the option to use the FOSS4G Ribbon, so I think we should put it back in the logo and keep the map pins without it.

**Comment by EdwinLiavaa** [comment]
Done!

**Comment by EdwinLiavaa** [comment]
You mean to replace the competition logo with the banner?

**Comment by jonah-sullivan** [comment]
Sorry I'm not being very clear. I'm still trying to develop an opinion. 

I was reading the OSGeo page about the OSGeo banner and it says that the banner is required for the global conference and optional for the regional conferences (like ours). So we don't have to use it.

I think we should use the version of the conference logo with the OSGeo ribbon at the top of the page.

Other uses, such as the map pins and other logos, get rid of the OSGeo ribbon.

How does that sound?

Nemaia made a nice version of the conference logo. I'll find it and send it to you.

**Comment by jonah-sullivan** [comment]
![online_conference](https://user-images.githubusercontent.com/11877822/93202759-924e9500-f796-11ea-9f99-372cac1c243b.jpg)

**Comment by EdwinLiavaa** [comment]
Very well received and noted for appropriate action.

**Comment by EdwinLiavaa** [comment]
Done!

**Comment by EdwinLiavaa** [comment]
Closing this issue.
