### ISSUE TITLE
add link to email contact for hubs

### ISSUE THREAD

**Issue by jonah-sullivan** [foss4g-oceania/foss4g-sotm-oceania-2020#32]
Please add a link to the email list within the "hubs" section so people can send queries: foss4g-oceania@lists.osgeo.org

somewhere above or below the map.

![image](https://user-images.githubusercontent.com/11877822/93547988-9b638000-f9a9-11ea-9e1b-fb4b8fa9d22b.png)

**Comment by EdwinLiavaa** [comment]
Done!
