### ISSUE TITLE
Add link to Call for Presentations form

### ISSUE THREAD

**Issue by jonah-sullivan** [foss4g-oceania/foss4g-sotm-oceania-2020#41]
The form link:
https://docs.google.com/forms/d/e/1FAIpQLSd8aZjlZvP5ArubK0DkcIfEUIZnyxZLy1pNFS0p4YafKSo4LA/viewform

I made a MS Paint edit:

![Screenshot 2020-09-30 134634](https://user-images.githubusercontent.com/11877822/94641001-6c42fc00-0323-11eb-905c-366b5dad3acf.jpg)

**Comment by jonah-sullivan** [comment]
There might already be a page, or heading for call for presentations. Please use this instead if it already exists.

I didn't see it, but my JavaScript skills are pretty bad.

**Comment by EdwinLiavaa** [comment]
Done!

**Comment by jonah-sullivan** [comment]
Thanks @FidelChe, we already got one submission.

**Comment by EdwinLiavaa** [comment]
Wow...awesome!
