### ISSUE TITLE
Add hub locations to sidebar

### ISSUE THREAD

**Issue by jonah-sullivan** [foss4g-oceania/foss4g-sotm-oceania-2020#52]
https://github.com/foss4g-oceania/foss4g-sotm-oceania-2020/blob/69f6d7d5612b07272e774971ae3e9c6c50fca694/_includes/about.html#L26

List of Hubs:

- Apia, Samoa
- Auckland, New Zealand [/hubs/auckland/]
- Bairiki, Kiribati
- Cairns, Australia
- Canberra, Australia [/hubs/canberra/]
- Christchurch, New Zealand
- Hobart, Australia
- Majuro, Marshall Islands
- Melbourne, Australia
- Perth, Australia [/hubs/perth/]
- Rarotonga, Cook Islands
- Suva, Fiji

**Comment by jonah-sullivan** [comment]
solved by #53

**Comment by EdwinLiavaa** [comment]
Awesome Jonah..we just love FOSS :)
