### ISSUE TITLE
Change logo to date instead of "online"

### ISSUE THREAD

**Issue by jonah-sullivan** [foss4g-oceania/foss4g-sotm-oceania-2020#57]
I made a new version of the logo with the conference date instead of "online" because the conference isn't JUST online, it's also in-person.

I made a PNG version because there might be a rendering problem with the SVG text. Might have to convert the SVG text to paths to ensure it renders correctly.

The logo is saved as PNG and SVG:
SVG: https://drive.google.com/file/d/18eqdUPJRm43oQpuCxqvrjcwbMeif6_N1/view?usp=sharing
PNG: https://drive.google.com/file/d/1zLfWn19vyZaY7tnw1fS5h6EE6HaF0Lec/view?usp=sharing

I can't figure out where to edit the website to make the changes, please change the logo at the top and bottom of the website.

**Comment by jonah-sullivan** [comment]
@keithamoss  @FidelChe

**Comment by jonah-sullivan** [comment]
@om-henners

**Comment by EdwinLiavaa** [comment]
Very well noted Jonah..cheers!

**Comment by jonah-sullivan** [comment]
Sorry about the spam @FidelChe, I was demonstrating how to raise issues and pull requests for the conference website.

Henry Walshaw (@om-henners) is going to get access too so he can help out.
