### ISSUE TITLE
Add code of conduct

### ISSUE THREAD

**Issue by adamsteer** [foss4g-oceania/foss4g-sotm-oceania-2020#9]
we should create a code of conduct. The contributors covenant should be fine (?)

**Comment by jonah-sullivan** [comment]
I reckon.

**Comment by adamsteer** [comment]
I forgot to specify ‘a code of conduct for this repository’. A code of conduct doc for the conference is another issue :) I’d recommend the OSGeo code of conduct (or some mashup of the OSGeo and SotM ones) for that…

**Comment by EdwinLiavaa** [comment]
Agree

**Comment by EdwinLiavaa** [comment]
Have added OSGeo code of conduct

**Comment by jonah-sullivan** [comment]
That sure is a fancy code of conduct.

**Comment by jonah-sullivan** [comment]
I'll get write access so I can help out more.

**Comment by EdwinLiavaa** [comment]
Cool

**Comment by jonah-sullivan** [comment]
Recommend close this issue.

**Comment by EdwinLiavaa** [comment]
Look good..agree
